### ISSUE TITLE
[Web][Admin] Unable to edit banners

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#132]
1. Login as Admin
2. Go to Masters->banners
3. Add a Banner
4. Try to Edit banner

Actual result: Edit banner is not available, only delete option is available.
Expected result: Edit option should be available.

![image](https://user-images.githubusercontent.com/101229315/212431458-af8c022f-9b98-4c08-8588-8adc58be76de.png)

**Comment by eraytech** [comment]
Banners are not displaying at specified location. The current banner has to display at "Saved Jobs" page and the expiry date is changed to 01/18/2023 so it is still valid. But when "Saved Jobs" page is opened, there is no banner.

![image](https://user-images.githubusercontent.com/101229315/212931754-4146211a-25ef-493e-a97f-3acb362e9b6b.png)

**Comment by Abhinavgunda25** [comment]
Issue is Resolved., Please check

**Comment by eraytech** [comment]
Banner deactivated, but still displays on user page.
When banner is deactivated, it shall not display in DearJob website.

Deactivated in admin page:
![image](https://github.com/gak112/DearJobTesting/assets/101229315/f12fb99d-65b1-4010-89b4-0df65c2f864d)

Banner still shows in Saved jobs page:
![image](https://github.com/gak112/DearJobTesting/assets/101229315/755c2d79-9249-4a02-ac30-91cadb550376)

**Comment by eraytech** [comment]
banner is not getting deactivated based on expire date.
